<a href="https://colab.research.google.com/github/ghizlane89/0__GenIA/blob/Bootcamp/W3_D1_EX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

#Exercice 1

import numpy as np


array_1 = np.arange(10)
print("Array:", array_1)



Array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# Exercice 2

import numpy as np


liste = [3.14, 2.17, 0, 1, 2]

# Convert to NumPy array and change type to integer
array_1 = np.array(liste, dtype=int)
print( array_1)


[3 2 0 1 2]


In [4]:
# Exercice 3


import numpy as np

array = np.arange(1, 10).reshape(3, 3)
print("3x3 Array:\n", array)

3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Exercice 4

np.random.rand(4, 5)


array([[0.99895263, 0.51535274, 0.73811712, 0.84425271, 0.44169109],
       [0.00971682, 0.29543381, 0.57579728, 0.16391823, 0.9416682 ],
       [0.778761  , 0.62682567, 0.47302403, 0.47407267, 0.80680042],
       [0.01553075, 0.67343563, 0.25210666, 0.82819009, 0.21840721]])

In [6]:
# Exercice 5

array = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])

Ligne2 = array[1]

print(Ligne2)

[20 21 22 23 24]


In [9]:
# Exercice 6

array = np.arange(10)

# Reverse the array using slicing
reversed_arr = array[::-1]

print("Reversed array:", reversed_arr)





Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [10]:
# Exercice 7

identity_matrix = np.eye(4)

print(identity_matrix)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Exercice 8

arr = np.arange(10)

total = np.sum(arr)
average = np.mean(arr)

print("Sum:", total, "Average:", average)


Sum: 45 Average: 4.5


In [12]:
# Exercice 9

import numpy as np

# Create a 1D array from 1 to 20
arr = np.arange(1, 21)

# Reshape it into a 4x5 matrix
reshaped_arr = arr.reshape(4, 5)

print( reshaped_arr)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
# Exercice 10

import numpy as np

# Given array (example)
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract only odd numbers
odd_numbers = arr[arr % 2 == 1]

print("Odd numbers:", odd_numbers)





Odd numbers: [1 3 5 7 9]
